package military.models;

// ============================================================
// SupplyRequest.java
// Represents a request raised by a warehouse to get stock
// from a higher-level warehouse.
// isReplenishment = true means the system auto-generated it
// after stock fell below threshold.
// ============================================================

public class SupplyRequest {

    public int     requestId;
    public String  requester;       // Warehouse that raised the request
    public String  itemName;
    public int     quantity;
    public String  status;          // "PENDING" or "APPROVED_FOR_DELIVERY"
    public boolean isReplenishment; // True if auto-generated by replenishment logic

    // Standard manual request
    public SupplyRequest(int requestId, String requester, String itemName,
                         int quantity, String status) {
        this.requestId       = requestId;
        this.requester       = requester;
        this.itemName        = itemName;
        this.quantity        = quantity;
        this.status          = status;
        this.isReplenishment = false;
    }

    // Auto-generated replenishment request
    public SupplyRequest(int requestId, String requester, String itemName,
                         int quantity, String status, boolean isReplenishment) {
        this.requestId       = requestId;
        this.requester       = requester;
        this.itemName        = itemName;
        this.quantity        = quantity;
        this.status          = status;
        this.isReplenishment = isReplenishment;
    }
}
